# Generated by Django 6.0 on 2026-04-08 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='photo',
        ),
        migrations.AddField(
            model_name='tweet',
            name='photo_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
